name: Build EvoFileManagerDialog
on:
  release:
    types: [ created ]

jobs:
  run:
    name: Build EvoFileManagerDialog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm run inst

      - name: Update source code
        run: npm run build

      - name: Commit changes
        uses: EndBug/add-and-commit@v10
        with:
          author_name: ProjectSoft-STUDIONIONS
          author_email: projectsoft2009@yandex.ru
          add: |
            - **/*.js
            - **/*.css
            - **/*.less
            - **/*.php
            - **/*.tpl

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: EvoFileManagerDialog.zip
          tag: ${{ github.ref_name }}
          overwrite: true
          file_glob: true
